import type { FormTemplate } from '../types';

export const FORM_TEMPLATES: FormTemplate[] = [
  {
    id: 'customer-feedback',
    name: 'Customer Feedback Survey',
    description: 'Gather insights about customer satisfaction and experience',
    category: 'feedback',
    icon: 'fa-comments',
    preview_text: '5 questions • 2 min',
    background_color: '#e1f5fe',
    questions_template: [
      {
        id: 'q1',
        type: 'text',
        title: 'What is your name?',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q2',
        type: 'rating',
        title: 'How satisfied are you with our service?',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q3',
        type: 'multiple-choice',
        title: 'What aspect did you like the most?',
        options: ['Product Quality', 'Customer Service', 'Pricing', 'Delivery Speed'],
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q4',
        type: 'long-text',
        title: 'What could we improve?',
        required: false,
        placeholder: 'Your suggestions...',
        exitAnimation: 'slide',
      },
      {
        id: 'q5',
        type: 'email',
        title: 'Can we contact you?',
        required: false,
        exitAnimation: 'slide',
      },
    ],
  },
  {
    id: 'event-registration',
    name: 'Event Registration Form',
    description: 'Register attendees for your event',
    category: 'registration',
    icon: 'fa-ticket',
    preview_text: '6 questions • 3 min',
    background_color: '#fed7aa',
    questions_template: [
      {
        id: 'q1',
        type: 'text',
        title: 'Full Name',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q2',
        type: 'email',
        title: 'Email Address',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q3',
        type: 'phone',
        title: 'Phone Number',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q4',
        type: 'text',
        title: 'Company/Organization',
        required: false,
        exitAnimation: 'slide',
      },
      {
        id: 'q5',
        type: 'multiple-choice',
        title: 'Which session are you interested in?',
        options: ['Session A (9 AM)', 'Session B (1 PM)', 'Session C (3 PM)'],
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q6',
        type: 'checkboxes',
        title: 'Dietary restrictions?',
        options: ['Vegetarian', 'Vegan', 'Gluten-free', 'No restrictions'],
        required: false,
        exitAnimation: 'slide',
      },
    ],
  },
  {
    id: 'job-application',
    name: 'Job Application',
    description: 'Streamline your hiring with structured applications',
    category: 'jobs',
    icon: 'fa-briefcase',
    preview_text: '7 questions • 5 min',
    background_color: '#ddd6fe',
    questions_template: [
      {
        id: 'q1',
        type: 'text',
        title: 'Full Name',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q2',
        type: 'email',
        title: 'Email',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q3',
        type: 'phone',
        title: 'Phone Number',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q4',
        type: 'text',
        title: 'Desired Position',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q5',
        type: 'long-text',
        title: 'Tell us about your experience',
        required: true,
        placeholder: 'Share your relevant work experience...',
        exitAnimation: 'slide',
      },
      {
        id: 'q6',
        type: 'long-text',
        title: 'Why do you want to join us?',
        required: true,
        placeholder: 'Tell us your motivation...',
        exitAnimation: 'slide',
      },
      {
        id: 'q7',
        type: 'image-upload',
        title: 'Upload your resume',
        required: true,
        acceptedFormats: 'image/jpeg,image/png,application/pdf',
        maxFileSize: 5,
        exitAnimation: 'slide',
      },
    ],
  },
  {
    id: 'lead-capture',
    name: 'Lead Capture Form',
    description: 'Collect leads for your business',
    category: 'capture',
    icon: 'fa-bullseye',
    preview_text: '4 questions • 1 min',
    background_color: '#fef08a',
    questions_template: [
      {
        id: 'q1',
        type: 'text',
        title: "What's your name?",
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q2',
        type: 'email',
        title: 'Email',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q3',
        type: 'text',
        title: 'Company name',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q4',
        type: 'dropdown',
        title: 'How can we help you?',
        options: ['Sales Inquiry', 'Support', 'Partnership', 'Other'],
        required: true,
        exitAnimation: 'slide',
      },
    ],
  },
  {
    id: 'nps-survey',
    name: 'NPS (Net Promoter Score) Survey',
    description: 'Measure customer loyalty with NPS',
    category: 'nps',
    icon: 'fa-chart-line',
    preview_text: '3 questions • 1 min',
    background_color: '#fda4af',
    questions_template: [
      {
        id: 'q1',
        type: 'rating',
        title: 'How likely are you to recommend us to a friend (0-10)?',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q2',
        type: 'long-text',
        title: 'Why did you choose that score?',
        required: true,
        placeholder: 'Your thoughts...',
        exitAnimation: 'slide',
      },
      {
        id: 'q3',
        type: 'email',
        title: 'Email (optional)',
        required: false,
        exitAnimation: 'slide',
      },
    ],
  },
  {
    id: 'contact-form',
    name: 'Contact Form',
    description: 'Simple way to collect contact requests',
    category: 'contact',
    icon: 'fa-envelope',
    preview_text: '5 questions • 2 min',
    background_color: '#ddd6fe',
    questions_template: [
      {
        id: 'q1',
        type: 'text',
        title: 'Name',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q2',
        type: 'email',
        title: 'Email',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q3',
        type: 'phone',
        title: 'Phone (optional)',
        required: false,
        exitAnimation: 'slide',
      },
      {
        id: 'q4',
        type: 'text',
        title: 'Subject',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q5',
        type: 'long-text',
        title: 'Message',
        required: true,
        placeholder: 'Your message here...',
        exitAnimation: 'slide',
      },
    ],
  },
  {
    id: 'product-feedback',
    name: 'Product Feedback',
    description: 'Collect structured feedback on your product',
    category: 'feedback',
    icon: 'fa-lightbulb',
    preview_text: '6 questions • 3 min',
    background_color: '#fecaca',
    questions_template: [
      {
        id: 'q1',
        type: 'text',
        title: 'What feature would you like most?',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q2',
        type: 'rating',
        title: 'How easy is our product to use?',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q3',
        type: 'checkboxes',
        title: 'What issues have you encountered?',
        options: ['Performance', 'UI/UX', 'Documentation', 'Integrations', 'No issues'],
        required: false,
        exitAnimation: 'slide',
      },
      {
        id: 'q4',
        type: 'rating',
        title: 'Overall satisfaction',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q5',
        type: 'long-text',
        title: 'Any additional comments?',
        required: false,
        placeholder: 'Your feedback...',
        exitAnimation: 'slide',
      },
      {
        id: 'q6',
        type: 'email',
        title: 'Can we follow up with you?',
        required: false,
        exitAnimation: 'slide',
      },
    ],
  },
  {
    id: 'appointment-booking',
    name: 'Appointment Booking',
    description: 'Schedule appointments and consultations',
    category: 'booking',
    icon: 'fa-calendar',
    preview_text: '5 questions • 2 min',
    background_color: '#a5f3fc',
    questions_template: [
      {
        id: 'q1',
        type: 'text',
        title: "What's your name?",
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q2',
        type: 'email',
        title: 'Email',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q3',
        type: 'phone',
        title: 'Phone Number',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q4',
        type: 'date',
        title: 'Preferred appointment date',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q5',
        type: 'dropdown',
        title: 'Service type',
        options: ['Consultation', 'Demo', 'Support', 'Other'],
        required: true,
        exitAnimation: 'slide',
      },
    ],
  },
  {
    id: 'course-feedback',
    name: 'Course/Training Feedback',
    description: 'Collect feedback on courses and training sessions',
    category: 'feedback',
    icon: 'fa-graduation-cap',
    preview_text: '7 questions • 3 min',
    background_color: '#bfdbfe',
    questions_template: [
      {
        id: 'q1',
        type: 'text',
        title: 'Course/Training name',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q2',
        type: 'rating',
        title: 'How would you rate the course content?',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q3',
        type: 'rating',
        title: 'How well was it delivered?',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q4',
        type: 'rating',
        title: 'Would you recommend this course?',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q5',
        type: 'checkboxes',
        title: 'What topics would you like covered more?',
        options: ['Fundamentals', 'Advanced Topics', 'Practical Projects', 'Case Studies'],
        required: false,
        exitAnimation: 'slide',
      },
      {
        id: 'q6',
        type: 'long-text',
        title: 'What could be improved?',
        required: false,
        placeholder: 'Your suggestions...',
        exitAnimation: 'slide',
      },
      {
        id: 'q7',
        type: 'email',
        title: 'Email for updates',
        required: false,
        exitAnimation: 'slide',
      },
    ],
  },
  {
    id: 'support-ticket',
    name: 'Support Request',
    description: 'Help customers submit support requests',
    category: 'support',
    icon: 'fa-headset',
    preview_text: '6 questions • 3 min',
    background_color: '#fbcfe8',
    questions_template: [
      {
        id: 'q1',
        type: 'text',
        title: 'Your name',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q2',
        type: 'email',
        title: 'Email',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q3',
        type: 'dropdown',
        title: 'Issue category',
        options: ['Technical Issue', 'Billing', 'Feature Request', 'Bug Report', 'Other'],
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q4',
        type: 'text',
        title: 'Issue title',
        required: true,
        exitAnimation: 'slide',
      },
      {
        id: 'q5',
        type: 'long-text',
        title: 'Describe the issue',
        required: true,
        placeholder: 'Provide details about your issue...',
        exitAnimation: 'slide',
      },
      {
        id: 'q6',
        type: 'dropdown',
        title: 'Priority',
        options: ['Low', 'Medium', 'High', 'Urgent'],
        required: true,
        exitAnimation: 'slide',
      },
    ],
  },
];

export const TEMPLATE_CATEGORIES = [
  { id: 'all', name: 'All Templates', icon: 'fa-star' },
  { id: 'feedback', name: 'Feedback & Surveys', icon: 'fa-comments' },
  { id: 'registration', name: 'Registration', icon: 'fa-ticket' },
  { id: 'jobs', name: 'Hiring', icon: 'fa-briefcase' },
  { id: 'capture', name: 'Lead Capture', icon: 'fa-bullseye' },
  { id: 'nps', name: 'NPS', icon: 'fa-chart-line' },
  { id: 'contact', name: 'Contact', icon: 'fa-envelope' },
  { id: 'booking', name: 'Booking', icon: 'fa-calendar' },
  { id: 'support', name: 'Support', icon: 'fa-headset' },
];
